import sys
import re

def make_idempotent(filepath):
    with open(filepath, 'r') as f:
        content = f.read()

    if 'def upgrade() -> None:' not in content:
        return
        
    injection = """
    conn = op.get_bind()
    from sqlalchemy import inspect
    inspector = inspect(conn)
    tables = inspector.get_table_names()
"""
    
    content = content.replace('def upgrade() -> None:\n    """Upgrade schema."""\n    # ### commands auto generated by Alembic - please adjust! ###', 'def upgrade() -> None:\n    """Upgrade schema."""' + injection)

    def repl(m):
        table_name = m.group(1)
        return f"if '{table_name}' not in tables:\n        op.create_table('{table_name}'"
        
    content = re.sub(r"op\.create_table\('([^']+)'", repl, content)
    
    with open(filepath, 'w') as f:
        f.write(content)

make_idempotent('alembic/versions/d061cfa82751_add_reasoning_and_memory_tables.py')
make_idempotent('alembic/versions/03d582597c20_initial_schema.py')
