"""Add schema invariants

Revision ID: 3660ad06ce3c
Revises: 03d582597c20
Create Date: 2026-09-23 14:28:44.702969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3660ad06ce3c'
down_revision: Union[str, Sequence[str], None] = '03d582597c20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    from sqlalchemy import inspect
    inspector = inspect(conn)
    
    def has_index(table_name, index_name):
        return any(idx['name'] == index_name for idx in inspector.get_indexes(table_name))
        
    def has_constraint(table_name, constraint_name):
        return any(uc['name'] == constraint_name for uc in inspector.get_unique_constraints(table_name))
        

    # ### commands auto generated by Alembic - please adjust! ###
    if not has_index('learning_sessions', 'ix_learning_sessions_notebook_status'):
        op.create_index('ix_learning_sessions_notebook_status', 'learning_sessions', ['notebook_id', 'status'], unique=False)
    if not has_index('problem_attempts', 'ix_problem_attempts_session_status'):
        op.create_index('ix_problem_attempts_session_status', 'problem_attempts', ['learning_session_id', 'status'], unique=False)
    if not has_index('reasoning_steps', 'ix_reasoning_steps_attempt_seq'):
        op.create_index('ix_reasoning_steps_attempt_seq', 'reasoning_steps', ['attempt_id', 'sequence_number'], unique=False)
    if not has_constraint('reasoning_steps', 'uq_reasoning_step_attempt_seq'):
        with op.batch_alter_table('reasoning_steps') as batch_op:
            batch_op.create_unique_constraint('uq_reasoning_step_attempt_seq', ['attempt_id', 'sequence_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    conn = op.get_bind()
    from sqlalchemy import inspect
    inspector = inspect(conn)
    def has_constraint(table_name, constraint_name):
        return any(uc['name'] == constraint_name for uc in inspector.get_unique_constraints(table_name))

    # ### commands auto generated by Alembic - please adjust! ###
    if has_constraint('reasoning_steps', 'uq_reasoning_step_attempt_seq'):
        with op.batch_alter_table('reasoning_steps') as batch_op:
            batch_op.drop_constraint('uq_reasoning_step_attempt_seq', type_='unique')
    op.drop_index('ix_reasoning_steps_attempt_seq', table_name='reasoning_steps')
    op.drop_index('ix_problem_attempts_session_status', table_name='problem_attempts')
    op.drop_index('ix_learning_sessions_notebook_status', table_name='learning_sessions')
    # ### end Alembic commands ###
