"""Add group_id and group_revision to reasoning_steps

Revision ID: 4996ac6ad613
Revises: 3660ad06ce3c
Create Date: 2026-09-24 07:59:34.210446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4996ac6ad613'
down_revision: Union[str, Sequence[str], None] = '3660ad06ce3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reasoning_steps', sa.Column('group_id', sa.String(), nullable=True))
    op.add_column('reasoning_steps', sa.Column('group_revision', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reasoning_steps', 'group_revision')
    op.drop_column('reasoning_steps', 'group_id')
    # ### end Alembic commands ###
