"""Update graph models for Phase 3 batch mode

Revision ID: 6f9fbf64e222
Revises: 2788c95f1c69
Create Date: 2026-09-24 10:36:28.566542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f9fbf64e222'
down_revision: Union[str, Sequence[str], None] = '2788c95f1c69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS _alembic_tmp_concept_edges")
    op.execute("DROP TABLE IF EXISTS _alembic_tmp_concept_nodes")

    conn = op.get_bind()
    from sqlalchemy import inspect
    inspector = inspect(conn)
    tables = inspector.get_table_names()

    with op.batch_alter_table('concept_edges', schema=None) as batch_op:
        batch_op.alter_column('source_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('target_name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    if 'concept_nodes' in tables:
        existing_cols = [c['name'] for c in inspector.get_columns('concept_nodes')]
        cols_to_add = [
            ('canonical_key', sa.Column('canonical_key', sa.String(), nullable=False, server_default='')),
            ('display_name', sa.Column('display_name', sa.String(), nullable=False, server_default='')),
            ('node_type', sa.Column('node_type', sa.String(), nullable=False, server_default='CONCEPT')),
            ('aliases_json', sa.Column('aliases_json', sa.String(), nullable=True)),
            ('evidence_count', sa.Column('evidence_count', sa.Integer(), nullable=True)),
            ('extraction_method', sa.Column('extraction_method', sa.String(), nullable=True)),
            ('confidence', sa.Column('confidence', sa.Float(), nullable=True)),
            ('created_at', sa.Column('created_at', sa.DateTime(), nullable=True)),
            ('updated_at', sa.Column('updated_at', sa.DateTime(), nullable=True)),
        ]
        cols_to_drop = ['category', 'name']

        needs_add = [col for name, col in cols_to_add if name not in existing_cols]
        needs_drop = [name for name in cols_to_drop if name in existing_cols]

        if needs_add or needs_drop:
            with op.batch_alter_table('concept_nodes', schema=None) as batch_op:
                for col in needs_add:
                    batch_op.add_column(col)
                for name in needs_drop:
                    batch_op.drop_column(name)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('concept_nodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('category', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('confidence')
        batch_op.drop_column('extraction_method')
        batch_op.drop_column('evidence_count')
        batch_op.drop_column('aliases_json')
        batch_op.drop_column('node_type')
        batch_op.drop_column('display_name')
        batch_op.drop_column('canonical_key')

    with op.batch_alter_table('concept_edges', schema=None) as batch_op:
        batch_op.drop_constraint('fk_concept_edges_target_node_id', type_='foreignkey')
        batch_op.drop_constraint('fk_concept_edges_source_node_id', type_='foreignkey')
        batch_op.alter_column('target_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('source_name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
