"""Update graph models for Phase 3 batch mode

Revision ID: 6f9fbf64e222
Revises: 2788c95f1c69
Create Date: 2026-09-24 10:36:28.566542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f9fbf64e222'
down_revision: Union[str, Sequence[str], None] = '2788c95f1c69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concept_edges', schema=None) as batch_op:
        batch_op.alter_column('source_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('target_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_foreign_key('fk_concept_edges_target_node_id', 'concept_nodes', ['target_node_id'], ['id'])
        batch_op.create_foreign_key('fk_concept_edges_source_node_id', 'concept_nodes', ['source_node_id'], ['id'])

    with op.batch_alter_table('concept_nodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('canonical_key', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('display_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('node_type', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('aliases_json', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('evidence_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('extraction_method', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('category')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('concept_nodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('category', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('confidence')
        batch_op.drop_column('extraction_method')
        batch_op.drop_column('evidence_count')
        batch_op.drop_column('aliases_json')
        batch_op.drop_column('node_type')
        batch_op.drop_column('display_name')
        batch_op.drop_column('canonical_key')

    with op.batch_alter_table('concept_edges', schema=None) as batch_op:
        batch_op.drop_constraint('fk_concept_edges_target_node_id', type_='foreignkey')
        batch_op.drop_constraint('fk_concept_edges_source_node_id', type_='foreignkey')
        batch_op.alter_column('target_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('source_name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
