"""Add indexes to SubjectChunk

Revision ID: ecb5ad7a15e6
Revises: febdd314c89e
Create Date: 2026-09-24 21:12:31.682259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecb5ad7a15e6'
down_revision: Union[str, Sequence[str], None] = 'febdd314c89e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
