"""
Data models for the Manim AI Video Generator pipeline.

VideoJob is the shared LangGraph state object passed between agent nodes.
AnnotationEvent mirrors the frontend AnnotationEvent TypeScript interface.
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import List, Optional, Dict, Any, Tuple


class JobStatus(str, Enum):
    PENDING = "pending"
    PROCESSING = "processing"
    DONE = "done"
    ERROR = "error"


@dataclass
class PathData:
    """One freehand path drawn by the user on the annotation canvas."""
    points: List[Tuple[float, float]] = field(default_factory=list)  # normalized 0-1 coords
    stroke_color: str = "#ef4444"
    stroke_width: int = 3


@dataclass
class AnnotationEvent:
    """
    Mirrors the frontend AnnotationEvent TypeScript interface.
    One element of the /annotate request annotations[] array.
    """
    timestamp: float                         # video.currentTime (seconds) when user paused
    frame_image: str = ""                    # base64 PNG: video frame + drawn paths composited
    paths: List[PathData] = field(default_factory=list)  # raw path data for programmatic use
    comment: str = ""                        # user's question or note


@dataclass
class VideoJob:
    """
    LangGraph state object. Passed between all agent nodes in the pipeline.
    Only deltas are persisted per step (DeltaChannel).
    """
    # Required fields
    job_id: str
    user_prompt: str
    document_text: str = ""          # plain text extracted from PDF by DocumentEmbedder

    page_range: Optional[str] = None        
    emphasis_note: Optional[str] = None
    output_type: str = "video"              
    subject_id: Optional[str] = None

    # Optional fields with defaults
    pdf_path: str = ""               # temp file path for PDF bytes
    status: JobStatus = JobStatus.PENDING
    step: str = "init"
    progress_percentage: int = 0

    story_script: Optional[str] = None      # generated by StoryAgent
    manim_code: Optional[str] = None        # generated by CodeGenAgent
    video_path: Optional[str] = None        # local .mp4 path set by RendererAgent
    video_url: Optional[str] = None         # DO Spaces URL set by UploaderAgent
    stitched_video_url: Optional[str] = None

    # CI / retry state
    retry_count: int = 0                    # CodeGenAgent retry counter (max 3)
    has_build_error: bool = False           # set by CIPipeline
    build_error_trace: Optional[str] = None # stderr from failed manim dry-run

    # Story revision state
    revision_count: int = 0
    needs_revision: bool = False            # set by ValidatorAgent

    # Annotation
    annotations: List[AnnotationEvent] = field(default_factory=list)
    annotation_context: Dict[str, Any] = field(default_factory=dict)  # set by AnnotationHandler

    version: int = 1
    error_message: Optional[str] = None
    metadata: Dict[str, Any] = field(default_factory=dict)
    created_at: datetime = field(default_factory=datetime.utcnow)


@dataclass
class LatexJob:
    """
    LangGraph state object for the LaTeX conversion pipeline.
    """
    job_id: str
    image_b64: str                     # base64 encoded QPixmap image of handwriting
    template_type: str                 # "Assignment", "Research Paper", "Homework", "Lecture Slides"
    mode: str = "study"
    classroom_action: str = "Solve Question"

    status: JobStatus = JobStatus.PENDING
    step: str = "init"
    progress_percentage: int = 0
    
    raw_transcription: Optional[str] = None  # output of transcribe step
    structured_latex: Optional[str] = None   # output of structure step
    final_tex_code: Optional[str] = None     # output of template_apply step
    pdf_path: Optional[str] = None           # output of render step
    pdf_url: Optional[str] = None            # if uploaded
    
    retry_count: int = 0
    has_build_error: bool = False
    build_error_trace: Optional[str] = None
    
    error_message: Optional[str] = None
